local h = require("tests.helpers")
local Message = require("emeth.message")

h.describe("Message", function()
  h.it("creates with string content", function()
    local msg = Message:new("user", "hello")
    h.eq("user", msg.role)
    h.eq(1, #msg.content)
    h.eq("text", msg.content[1].type)
    h.eq("hello", msg.content[1].text)
    h.is_true(msg.uuid ~= nil)
    h.is_true(msg.timestamp ~= nil)
    h.eq(true, msg.visible)
  end)

  h.it("creates with table content", function()
    local msg = Message:new("assistant", { { type = "text", text = "hi" } })
    h.eq("table", type(msg.content))
    h.eq(1, #msg.content)
    h.eq("text", msg.content[1].type)
  end)

  h.it("wraps single ContentItem in a list", function()
    local msg = Message:new("assistant", { type = "thinking", thinking = "hmm" })
    h.eq("table", type(msg.content))
    h.eq(1, #msg.content)
    h.eq("thinking", msg.content[1].type)
  end)

  h.it("stores metadata", function()
    local msg = Message:new("user", "hi", { provider = "test" })
    h.eq("test", msg.metadata.provider)
  end)

  h.it("defaults metadata to empty table", function()
    local msg = Message:new("user", "hi")
    h.eq("table", type(msg.metadata))
  end)

  h.it("generates unique uuids", function()
    local a = Message:new("user", "a")
    local b = Message:new("user", "b")
    h.is_true(a.uuid ~= b.uuid)
  end)

  h.it("append_text to string content", function()
    local msg = Message:new("assistant", "hello")
    msg:append_text(" world")
    h.eq("hello world", msg.content[1].text)
  end)

  h.it("append_text to table content with existing text item", function()
    local msg = Message:new("assistant", { { type = "text", text = "hello" } })
    msg:append_text(" world")
    h.eq("hello world", msg.content[1].text)
  end)

  h.it("append_text to table content without text item adds one", function()
    local msg = Message:new("assistant", { { type = "thinking", thinking = "hmm" } })
    msg:append_text("new text")
    h.eq(2, #msg.content)
    h.eq("text", msg.content[2].type)
    h.eq("new text", msg.content[2].text)
  end)
end)
